trigger:
  branches:
    include:
      - dependabot/maven/org.springframework.boot-spring-boot-starter-parent-3.4.5

variables:
   cxAdditionalParams: '--file-filter "!src/test/**"'
   
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      name: Azure Pipelines
    steps:
    - task: Checkmarx AST@3
      displayName: 'Run Checkmarx One Scan'
      inputs:
        CheckmarxService: 'CxOne Connection'
        projectName: 'Rakshhii/webgoat-cx'
        branchName: 'dependabot/maven/org.springframework.boot-spring-boot-starter-parent-3.4.5'
        tenantName: 'cx_ind_internal_test'
        additionalParams: "$(cxAdditionalParams)"
