trigger:
  branches:
    include:
      - dependabot/maven/org.springframework.boot-spring-boot-starter-parent-3.4.5

pool:
  name: Rakshi_CX  # Your self-hosted agent pool

steps:
- task: Checkmarx AST@3
  displayName: 'Run Checkmarx One Scan'
  inputs:
    CheckmarxService: 'CxOne Connection'
    projectName: 'Rakshhii/webgoat-cx'
    branchName: 'dependabot/maven/org.springframework.boot-spring-boot-starter-parent-3.4.5'
    tenantName: 'cx_ind_internal_test'
